name: CI/CD Beta

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    push:
        branches: ['develop']
    workflow_dispatch:

concurrency: ci-beta

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: 400937848925.dkr.ecr.us-east-1.amazonaws.com
    # github.repository as <account>/<repo>
    IMAGE_NAME: saia/chain-editor
    TAG_SUFFIX: beta

jobs:
    build:
        environment: Beta
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@master
              with:
                  aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_KEY }}
                  aws-region: 'us-east-1'

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              with:
                  mask-password: 'true'

            - uses: docker/setup-buildx-action@v1

            # Build and push Docker image with Buildx (don't push on PR)
            # https://github.com/docker/build-push-action
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_SUFFIX }}.${{ github.run_number }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args:

            - name: Checkout IaC repository
              uses: actions/checkout@v3
              with:
                  repository: genexuslabs/GBrain-Infra
                  ref: beta
                  ssh-key: ${{ secrets.DEPLOY_KEY }}

            - name: Trigger Deployment Saia GPT
              shell: pwsh
              run: |
                  # Setting git username and email to be able to push back to repo
                  git config --global user.email "actions@genexus.com"
                  git config --global user.name "Github Actions"

                  Write-Output "Running deploy.ps1"
                  Install-Module -Force -Name powershell-yaml
                  .\scripts\deploy.ps1 -WorkSpace . -TagName ${{ env.TAG_SUFFIX }}.${{ github.run_number }} -DeploymentEnv beta -Service flowise-chain-editor -YamlConfigName extra-beta
